routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get
//Route::post
//Route::put
//Route::delete
//Route::patch
//Route::options
Route::get('/', 'HomeController@index')->name('home');
Route::get('/product/{slug}', 'HomeController@single')->name('product.single');
Route::get('/cat/{cat}', 'Admin\\CategoryController@cat')->name('cat');

Route::prefix('cart')->name('cart.')->group(function (){

    Route::post('add','CartController@add')->name('add');
    Route::get('/','CartController@index')->name('index');
    Route::get('cancel','CartController@cancel')->name('cancel');
    Route::get('remove/{slug}','CartController@remove')->name('remove');

});

Route::prefix('checkout')->name('checkout.')->group(function (){
    Route::get('/','CheckoutController@index')->name('index');
});

//Route::get('admin/stores','Admin\\StoreController@index'); sem o route::prefixe
Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function (){//Para diminuir a redundancia

    Route::prefix('stores')->name('stores.')->group(function (){
        Route::get('/','StoreController@index')->name('index');//é possível colocar um apelido com o ->name
        Route::get('/create','StoreController@create')->name('create');
        Route::get('/{slug}','StoreController@single')->name('single');
        Route::post('/store','StoreController@store')->name('store');
        Route::get('/{store}/edit','StoreController@edit')->name('edit');
        Route::get('/delete/{store}','StoreController@delete')->name('delete');
        Route::post('/update/{store}','StoreController@update')->name('update');
    });

    Route::resource('categories','CategoryController');
    Route::post('photos/remove/', 'ProductPhotoController@remove_photo')->name('photo.remove');

    //Route::resource('products','ProductsController'); caso estivesse trabalhando assim, teria que transformar as ações em
    //que estão com put e delete em forms, com o método post

    Route::prefix('products')->name('products.')->group(function (){
        Route::get('/','ProductsController@index')->name('index');//é possível colocar um apelido com o ->name
        Route::get('/create','ProductsController@create')->name('create');
        Route::post('/store','ProductsController@store')->name('store');
        Route::get('/{product}/edit','ProductsController@edit')->name('edit');
        Route::get('/destroy/{product}','ProductsController@destroy')->name('destroy');
        Route::post('/update/{product}','ProductsController@update')->name('update');
    });

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



/*
Route::get('/model',function (){
   //$products =  \App\Product::all(); //Select * from products

    //$user = new \App\User();
    //Active record
   // $user = \App\User::find(1);
    //$user->name = 'alou';
    //$user->email = 'alou@aloua';
    //$user->password = bcrypt('12334578');
    //$user->save();

    //return \App\User::find(1);
    //return \App\User::where('name','alou')->get();

    /*
    $user = \App\User::create([
       'name' => 'jonnys',
       'email' => 'obrabo@brabo',
       'password' => bcrypt('121854'),
    ]);
    dd($user);
    return $user;


    $user = \App\User::find(42);
    $user->update([
        'name' => 'novo nome'
    ]);

    return \App\User::all();
});*/

resources/views/cart.blade.php
@extends('layouts.front')
@section('content')


    @if((session()->has('cart')))
@php
    $total = 0;
@endphp
    @foreach(session()->get('cart') as $item)
       @php
           $total += $item['price']*$item['amount']
       @endphp
        <div class="row">
            <div class="list-group" style="width: 80%;background-color: #3490dc" >

                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{$item['name']}}</h5>
                        <a href="{{route('cart.remove',['slug'=> $item['slug']])}}" class="btn btn-danger">Remover</a>
                    </div>
                    <p>Quantidade: {{$item['amount']}}</p>
                    <p class="mb-1">R${{number_format($item['price']*$item['amount'],'2', ',','.')}}</p>

            </div>
        </div>
    @endforeach
    <div class="row">
        <div class="col-md-3" style="right: 1.2%">
        <li class="list-group-item list-group-item-success">O total é:  R${{number_format($total,'2', ',','.')}}</li>
        </div>
        <div class="col-md-8" style="margin-top: 1%">
            <a style="color:whitesmoke;" class="btn btn-success" href="{{route('checkout.index')}}">Concluir compra</a>
            <a style="color: #f8fafc" class="btn btn-danger" href="{{route('cart.cancel')}}">Desistir da compra</a>
        </div>
    </div>
    @else
    <h1 style="text-align: center">Sem itens no carrinho</h1>
    @endif
@endsection

resources/views/category.blade.php
@extends('layouts.front')

@section('content')
    <h2>{{$category->name}}</h2>
    <div class="row">

        @foreach($category->products as $key => $p)

            <div class="col-md-4">
                <div class="card">
                    @if($p->photos->count())
                        <img src="{{asset('storage/'.$p->photos->first()->image)}}" style="width: 90%;height: 150px;margin-left: 5%" alt="">
                    @else
                        <img src="{{asset('assets/no-photo.jpg')}}" style="width: 90%;height: 150px;margin-left: 5%" alt="">
                    @endif
                    <div class="card-body">
                        <h2 class="card-title">{{$p->name}}</h2>
                        <p class="card-text">{{$p->description}}</p>
                        @if(isset($p->slug))
                            <a href="{{route('product.single',['slug'=>$p->slug])}}" class="btn btn-success">Info</a>
                        @endif
                    </div>
                </div>
            </div>
            @if(($key+1)%3 == 0)
    </div><div class="row front">
        @endif

        @endforeach
    </div>



@endsection

resources/views/checkout.blade.php
@extends('layouts.front')
@section('content')
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Compra efetuada!</h4>
        <p>Muito bem, se você chegou até aqui certamente conseguiu fechar uma compra.</p>
        <hr>
        <p class="mb-0">O seu carrinho foi zerado e iremos preparar o seu pedido para envio.</p>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/single.blade.php
@extends('layouts.front')
@section('content')
    <div class="row">
        <a href="{{route('home')}}" class="btn btn-info">Voltar</a>

            <div class="col-md-12">
                    @if($product->photos->count())
                        <img src="{{asset('storage/'.$product->photos->first()->image)}}" style="width: 70%;height: 150px;margin-left: 15%" alt="">
                    @else
                        <img src="{{asset('assets/no-photo.jpg')}}" style="width: 70%;height: 150px;margin-left: 15%" alt="">
                    @endif

            </div>
        <div class="col-md-8">
            <h2>{{$product->name}}</h2>
            <p >{{$product->description}}</p>
            <p >R$ {{number_format($product->price,'2', ',','.')}}</p>
            <p >Loja: {{$product->store->name}}</p>
        </div>
        <div class="col-md-4" style="float: right">
            <form method="post" action="{{route('cart.add')}}">
            @csrf
                <input type="hidden" name="product[name]" value="{{$product->name}}">
                <input type="hidden" name="product[price]" value="{{$product->price}}">
                <input type="hidden" name="product[slug]" value="{{$product->slug}}">
                <div class="form-group" >
                    <label>Quantidade</label>
                    <input name="product[amount]" type="number" class="form-control col-md-2" required value="1">
                </div>
            <button type="submit" style="color: #f8fafc" class="btn btn-lg btn-danger">Comprar</button>
            </form>
        </div>

    </div>

@endsection

resources/views/storesingle.blade.php
@extends('layouts.front')
@section('content')
    <div class="row">
        <a href="{{route('home')}}" class="btn btn-info">Voltar</a>

        <div class="col-md-12">
            @if($store->logo != null)
                <img src="{{asset('storage/'.$store->logo)}}" style="width: 70%;height: 150px;margin-left: 15%" alt="">
            @else
                <img src="{{asset('assets/no-photo.jpg')}}" style="width: 70%;height: 150px;margin-left: 15%" alt="">
            @endif

        </div>
        <div class="col-md-8">
            <h2>{{$store->name}}</h2>
            <p >{{$store->description}}</p>

        </div>

    </div>

@endsection