routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get
//Route::post
//Route::put
//Route::delete
//Route::patch
//Route::options
Route::get('/', 'HomeController@index')->name('home');
Route::get('/product/{slug}', 'HomeController@single')->name('product.single');
Route::get('/cat/{cat}', 'Admin\\CategoryController@cat')->name('cat');

Route::prefix('cart')->name('cart.')->group(function (){

    Route::post('add','CartController@add')->name('add');
    Route::get('/','CartController@index')->name('index');
    Route::get('cancel','CartController@cancel')->name('cancel');
    Route::get('remove/{slug}','CartController@remove')->name('remove');

});

Route::prefix('checkout')->name('checkout.')->group(function (){
    Route::get('/','CheckoutController@index')->name('index');
});

//Route::get('admin/stores','Admin\\StoreController@index'); sem o route::prefixe
Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function (){//Para diminuir a redundancia

    Route::prefix('stores')->name('stores.')->group(function (){
        Route::get('/','StoreController@index')->name('index');//é possível colocar um apelido com o ->name
        Route::get('/create','StoreController@create')->name('create');
        Route::get('/{slug}','StoreController@single')->name('single');
        Route::post('/store','StoreController@store')->name('store');
        Route::get('/{store}/edit','StoreController@edit')->name('edit');
        Route::get('/delete/{store}','StoreController@delete')->name('delete');
        Route::post('/update/{store}','StoreController@update')->name('update');
    });

    Route::resource('categories','CategoryController');
    Route::post('photos/remove/', 'ProductPhotoController@remove_photo')->name('photo.remove');

    //Route::resource('products','ProductsController'); caso estivesse trabalhando assim, teria que transformar as ações em
    //que estão com put e delete em forms, com o método post

    Route::prefix('products')->name('products.')->group(function (){
        Route::get('/','ProductsController@index')->name('index');//é possível colocar um apelido com o ->name
        Route::get('/create','ProductsController@create')->name('create');
        Route::post('/store','ProductsController@store')->name('store');
        Route::get('/{product}/edit','ProductsController@edit')->name('edit');
        Route::get('/destroy/{product}','ProductsController@destroy')->name('destroy');
        Route::post('/update/{product}','ProductsController@update')->name('update');
    });

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



/*
Route::get('/model',function (){
   //$products =  \App\Product::all(); //Select * from products

    //$user = new \App\User();
    //Active record
   // $user = \App\User::find(1);
    //$user->name = 'alou';
    //$user->email = 'alou@aloua';
    //$user->password = bcrypt('12334578');
    //$user->save();

    //return \App\User::find(1);
    //return \App\User::where('name','alou')->get();

    /*
    $user = \App\User::create([
       'name' => 'jonnys',
       'email' => 'obrabo@brabo',
       'password' => bcrypt('121854'),
    ]);
    dd($user);
    return $user;


    $user = \App\User::find(42);
    $user->update([
        'name' => 'novo nome'
    ]);

    return \App\User::all();
});*/

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Product extends Model

{
    use HasSlug;

    protected $fillable = ['name', 'description', 'body', 'price', 'slug'];
    public function store(){
        return $this->belongsTo(Store::class);
    }
    //

    public  function categories(){
        return $this->belongsToMany(Category::class);
    }

    public function photos(){
        return $this->hasMany(ProductPhoto::class);
    }
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }
}

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductsRequest;
use App\Product;
use Illuminate\Http\Request;


class ProductsController extends Controller
{
    private $product;
    public function __construct(Product $product){
        $this->product = $product;
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userStore = auth()->user()->stores;
        $products = $userStore->products()->paginate(10);
        //$products = $this->product->paginate(10);

        return view('admin.products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = \App\Category::all(['id','name']);
        $stores = \App\Store::all(['id','name']);
        return view('admin.products.create',compact(['categories','stores']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductsRequest $request)
    {


        $data = $request->all();


        $categories = $request->get('categories',null);
        //$store = \App\Store::find($data['store']);
        $store = auth()->user()->stores;
        $product = $store->products()->create($data);


        $product->categories()->sync($categories);

        if($request->hasFile('photos')){
                $images = $this->uploadphoto($request, 'image');
                //Inserção no banco
            $product->photos()->createMany($images);
        }


        flash('Produto criado com sucesso!')->success();
        return redirect()->route('admin.products.index');
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->product->find($id);
        return view('admin.products.show',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = \App\Category::all(['id','name']);
        $product = $this->product->find($id);
        return view('admin.products.edit',compact(['product','categories']));
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductsRequest $request, $id)
    {
        $data = $request->all();
        $product = $this->product->find($id);
        $product->update($data);
        $categories = $request->get('categories',null);
        if(!is_null($categories)){
            $product->categories()->sync($categories);
        }

        if($request->hasFile('photos')){
            $images = $this->uploadphoto($request, 'image');
            //Inserção no banco
            $product->photos()->createMany($images);
        }
        flash('Produto atualizado com sucesso!');
        return redirect()->route('admin.products.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = $this->product->find($id);
        $product->delete();
        flash('Produto removido com sucesso!');
        return redirect()->route('admin.products.index');
    }

    private function uploadphoto(Request $request, $imageColumn){
        $fotos = [];
        $images = $request->file('photos');
        foreach ($images as $i){
            $fotos [] = [$imageColumn => $i->store('products','public')];
        }

        return $fotos;
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.app')


@section('content')
    <h1>Criar Produto</h1>
    <form action="{{route('admin.products.store')}}" method="post" enctype="multipart/form-data">
        @csrf

        <div class="form-group">
            <label>Nome Produto</label>
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{old('name')}}">

            @error('name')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control @error('description') is-invalid @enderror" value="{{old('description')}}">

            @error('description')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Conteúdo</label>
            <textarea name="body" id="" cols="30" rows="10" class="form-control @error('body') is-invalid @enderror">{{old('body')}}</textarea>

            @error('body')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>


        <div class="form-group">
            <label>Preço</label>
            <input type="text" name="price" class="form-control @error('price') is-invalid @enderror" value="{{old('price')}}">

            @error('price')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Categoria</label>
            <select name="categories[]" multiple class="form-control">
                @foreach($categories as $c)
                    <option value="{{$c->id}}">{{$c->name}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label>Fotos do produto</label>
            <input type="file" name="photos[]" class="form-control @error('photos') is-invalid @enderror" multiple>
        </div>



        <div>
            <button type="submit" class="btn btn-lg btn-success">Criar Produto</button>
        </div>
    </form>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')


@section('content')
    <h1>Atualizar Produto</h1>

    <form action="{{route('admin.products.update', ['product' => $product->id])}}" method="post" enctype="multipart/form-data">
        @csrf


        <div class="form-group">
            <label>Nome Produto</label>
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{$product->name}}">

            @error('name')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control @error('description') is-invalid @enderror" value="{{$product->description}}">

            @error('description')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Conteúdo</label>
            <textarea name="body" id="" cols="30" rows="10" class="form-control @error('body') is-invalid @enderror">{{$product->body}}</textarea>

            @error('body')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>


        <div class="form-group">
            <label>Preço</label>
            <input type="text" name="price" class="form-control @error('price') is-invalid @enderror" value="{{$product->price}}">

            @error('price')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Categoria</label>
            <select name="categories[]" multiple class="form-control">
                @foreach($categories as $c)
                    <option  value="{{$c->id}}"
                        @if ($product->categories->contains($c)) selected @endif
                    >{{$c->name}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label>Fotos do produto</label>
            <input type="file" name="photos[]" class="form-control @error('photos') is-invalid @enderror" multiple>
        </div>



        <div>
            <button type="submit" class="btn btn-lg btn-success">Atualizar Produto</button>
        </div>
    </form>

    <hr>

    <div class="row">
        @foreach($product->photos as $photo)
            <div class="col-4">
                <img src="{{asset('storage/'.$photo->image)}}" class="img-fluid">
                <form action="{{route('admin.photo.remove', ['photo' => $photo->image])}}" method="post">
                    <input type="hidden" name="photo" value="{{$photo->image}}">
                    @csrf
                    <button  class="btn btn-danger" type="submit">Remover</button>
                </form>

            </div>
        @endforeach
    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{route('admin.products.create')}}"  class="btn btn-sm btn-success"> Criar Produto</a>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Preço</th>

            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        @foreach($products as $s)
            <tr>
                <td>{{$s->id}}</td>
                <td>{{$s->name}}</td>
                <td>{{$s->price}}</td>
                <td>

                    <a href="{{route('admin.products.edit',['product'=>$s->id])}}"  class="btn btn-sm btn-primary"> Editar</a>
                    <a href="{{route('admin.products.destroy',['product'=>$s->id])}}"  class="btn btn-sm btn-danger"> Deletar</a>


                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {{$products->links()}}

@endsection

resources/views/admin/products/show.blade.php
@extends('layouts.app')

@section('content')

<h1>
    Mostrando produto
</h1>
    <table class="table table-stripped">
        <thead>
        <td>ID</td>
        <td>Nome</td>
        <td>Preço</td>

        </thead>
        <tbody>
        <td>{{$data->id}}</td>
        <td>{{$data->name}}</td>
        <td>{{$data->price}}</td>
        </tbody>
    </table>


@endsection