routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get
//Route::post
//Route::put
//Route::delete
//Route::patch
//Route::options
Route::get('/', 'HomeController@index')->name('home');
Route::get('/product/{slug}', 'HomeController@single')->name('product.single');
Route::get('/cat/{cat}', 'Admin\\CategoryController@cat')->name('cat');

Route::prefix('cart')->name('cart.')->group(function (){

    Route::post('add','CartController@add')->name('add');
    Route::get('/','CartController@index')->name('index');
    Route::get('cancel','CartController@cancel')->name('cancel');
    Route::get('remove/{slug}','CartController@remove')->name('remove');

});

Route::prefix('checkout')->name('checkout.')->group(function (){
    Route::get('/','CheckoutController@index')->name('index');
});

//Route::get('admin/stores','Admin\\StoreController@index'); sem o route::prefixe
Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function (){//Para diminuir a redundancia

    Route::prefix('stores')->name('stores.')->group(function (){
        Route::get('/','StoreController@index')->name('index');//é possível colocar um apelido com o ->name
        Route::get('/create','StoreController@create')->name('create');
        Route::get('/{slug}','StoreController@single')->name('single');
        Route::post('/store','StoreController@store')->name('store');
        Route::get('/{store}/edit','StoreController@edit')->name('edit');
        Route::get('/delete/{store}','StoreController@delete')->name('delete');
        Route::post('/update/{store}','StoreController@update')->name('update');
    });

    Route::resource('categories','CategoryController');
    Route::post('photos/remove/', 'ProductPhotoController@remove_photo')->name('photo.remove');

    //Route::resource('products','ProductsController'); caso estivesse trabalhando assim, teria que transformar as ações em
    //que estão com put e delete em forms, com o método post

    Route::prefix('products')->name('products.')->group(function (){
        Route::get('/','ProductsController@index')->name('index');//é possível colocar um apelido com o ->name
        Route::get('/create','ProductsController@create')->name('create');
        Route::post('/store','ProductsController@store')->name('store');
        Route::get('/{product}/edit','ProductsController@edit')->name('edit');
        Route::get('/destroy/{product}','ProductsController@destroy')->name('destroy');
        Route::post('/update/{product}','ProductsController@update')->name('update');
    });

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



/*
Route::get('/model',function (){
   //$products =  \App\Product::all(); //Select * from products

    //$user = new \App\User();
    //Active record
   // $user = \App\User::find(1);
    //$user->name = 'alou';
    //$user->email = 'alou@aloua';
    //$user->password = bcrypt('12334578');
    //$user->save();

    //return \App\User::find(1);
    //return \App\User::where('name','alou')->get();

    /*
    $user = \App\User::create([
       'name' => 'jonnys',
       'email' => 'obrabo@brabo',
       'password' => bcrypt('121854'),
    ]);
    dd($user);
    return $user;


    $user = \App\User::find(42);
    $user->update([
        'name' => 'novo nome'
    ]);

    return \App\User::all();
});*/

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Mercado com Laravel</title>
</head>
<body>
@auth
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Crud Laravel</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item @if(request()->is('home')) active @endif">
                <a class="nav-link" href="{{route('home')}}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item @if(request()->is('admin/stores*')) active @endif">
                <a class="nav-link" href="{{route('admin.stores.index')}}">Stores</a>
            </li>
            <li class="nav-item @if(request()->is('admin/products*')) active @endif">
                <a class="nav-link" href="{{route('admin.products.index')}}">Products</a>
            </li>
            <li class="nav-item @if(request()->is('admin/categories*')) active @endif">
                <a class="nav-link" href="{{route('admin.categories.index')}}">Categories</a>
            </li>

        </ul>
            <div class="my-2 my-lg-0">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#" onclick="event.preventDefault();
                    document.getElementById('frm-logout').submit();">
                        Logout
                    </a>
                    <form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
                <li class="nav-item">
                    <span class="nav-link"> Bem vindo, {{auth()->user()->name}}</span>
                </li>
            </ul>
            </div>
    </div>
</nav>
@endauth
    <div class="container">
        @include('flash::message')
        @yield('content')
    </div>




<footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</footer>
</body>
</html>

resources/views/layouts/front.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Marketplace L6</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .front.row {
            margin-bottom: 40px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 40px;">

    <a class="navbar-brand" href="{{route('home')}}">Marketplace L6</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">
            <li class="nav-item @if(request()->is('home')) active @endif">
                <a class="nav-link" href="{{route('home')}}">Home <span class="sr-only">(current)</span></a>
            </li>

            @foreach($categories as $c)
                <li class="nav-item @if(request()->is('cat/'.$c->slug)) active @endif">
                    <a class="nav-link" href="{{route('cat',['cat'=>$c->slug])}}">{{$c->name}}</a>
                </li>
            @endforeach
        </ul>

        @auth
            <ul class="navbar-nav mr-auto">
                <li class="nav-item @if(request()->is('admin/stores*')) active @endif">
                    <a class="nav-link" href="{{route('admin.stores.index')}}">Lojas <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item @if(request()->is('admin/products*')) active @endif">
                    <a class="nav-link" href="{{route('admin.products.index')}}">Produtos</a>
                </li>
                <li class="nav-item @if(request()->is('admin/categories*')) active @endif">
                    <a class="nav-link" href="{{route('admin.categories.index')}}">Categorias</a>
                </li>

            </ul>
        @if(session()->has('cart'))
        <span>{{array_sum(array_column(session()->get('cart'),'amount'))}}</span>
            @endif
        <a href="{{route('cart.index')}}">
            <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-cart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
            </svg>
        </a>
            <div class="my-2 my-lg-0">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="event.preventDefault();
                                                                  document.querySelector('form.logout').submit(); ">Sair</a>

                        <form action="{{route('logout')}}" class="logout" method="POST" style="display:none;">
                            @csrf
                        </form>
                    </li>
                    <li class="nav-item">
                        <span class="nav-link">{{auth()->user()->name}}</span>
                    </li>
                </ul>
            </div>
        @endauth

    </div>
</nav>

<div class="container">
    @include('flash::message')
    @yield('content')
</div>
</body>
</html>