routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get
//Route::post
//Route::put
//Route::delete
//Route::patch
//Route::options
Route::get('/', 'HomeController@index')->name('home');
Route::get('/product/{slug}', 'HomeController@single')->name('product.single');
Route::get('/cat/{cat}', 'Admin\\CategoryController@cat')->name('cat');

Route::prefix('cart')->name('cart.')->group(function (){

    Route::post('add','CartController@add')->name('add');
    Route::get('/','CartController@index')->name('index');
    Route::get('cancel','CartController@cancel')->name('cancel');
    Route::get('remove/{slug}','CartController@remove')->name('remove');

});

Route::prefix('checkout')->name('checkout.')->group(function (){
    Route::get('/','CheckoutController@index')->name('index');
});

//Route::get('admin/stores','Admin\\StoreController@index'); sem o route::prefixe
Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function (){//Para diminuir a redundancia

    Route::prefix('stores')->name('stores.')->group(function (){
        Route::get('/','StoreController@index')->name('index');//é possível colocar um apelido com o ->name
        Route::get('/create','StoreController@create')->name('create');
        Route::get('/{slug}','StoreController@single')->name('single');
        Route::post('/store','StoreController@store')->name('store');
        Route::get('/{store}/edit','StoreController@edit')->name('edit');
        Route::get('/delete/{store}','StoreController@delete')->name('delete');
        Route::post('/update/{store}','StoreController@update')->name('update');
    });

    Route::resource('categories','CategoryController');
    Route::post('photos/remove/', 'ProductPhotoController@remove_photo')->name('photo.remove');

    //Route::resource('products','ProductsController'); caso estivesse trabalhando assim, teria que transformar as ações em
    //que estão com put e delete em forms, com o método post

    Route::prefix('products')->name('products.')->group(function (){
        Route::get('/','ProductsController@index')->name('index');//é possível colocar um apelido com o ->name
        Route::get('/create','ProductsController@create')->name('create');
        Route::post('/store','ProductsController@store')->name('store');
        Route::get('/{product}/edit','ProductsController@edit')->name('edit');
        Route::get('/destroy/{product}','ProductsController@destroy')->name('destroy');
        Route::post('/update/{product}','ProductsController@update')->name('update');
    });

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



/*
Route::get('/model',function (){
   //$products =  \App\Product::all(); //Select * from products

    //$user = new \App\User();
    //Active record
   // $user = \App\User::find(1);
    //$user->name = 'alou';
    //$user->email = 'alou@aloua';
    //$user->password = bcrypt('12334578');
    //$user->save();

    //return \App\User::find(1);
    //return \App\User::where('name','alou')->get();

    /*
    $user = \App\User::create([
       'name' => 'jonnys',
       'email' => 'obrabo@brabo',
       'password' => bcrypt('121854'),
    ]);
    dd($user);
    return $user;


    $user = \App\User::find(42);
    $user->update([
        'name' => 'novo nome'
    ]);

    return \App\User::all();
});*/

app/Category.php
<?php

namespace App;

use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    use HasSlug;
    protected $fillable = ['name','description', 'slug'];

    public function products(){
        return $this->belongsToMany(Product::class);
    }
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;

class CategoryController extends Controller
{
    /**
     * @var Category
     */
    private $category;

    public function __construct(Category $category)
    {
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->category->paginate(10);

        return view('admin.categories.index', compact('categories'));
    }

    public function cat($cat)
    {
        $category = $this->category->where('slug',$cat)->first();

       return view('category', compact('category'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CategoryRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $data = $request->all();

        $category = $this->category->create($data);

        flash('Categoria Criado com Sucesso!')->success();
        return redirect()->route('admin.categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($category)
    {
        $category = $this->category->findOrFail($category);

        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CategoryRequest $request
     * @param  int $category
     *
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $category)
    {
        $data = $request->all();

        $category = $this->category->find($category);
        $category->update($data);

        flash('Categoria Atualizada com Sucesso!')->success();
        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($category)
    {
        $category = $this->category->find($category);
        $category->delete();

        flash('Categoria Removida com Sucesso!')->success();
        return redirect()->route('admin.categories.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')


@section('content')
    <h1>Criar Categoria</h1>
    <form action="{{route('admin.categories.store')}}" method="post">
        <input type="hidden" name="_token" value="{{csrf_token()}}">
        <div class="form-group">
            <label>Nome</label>
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{old('name')}}">

            @error('name')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control @error('description') is-invalid @enderror" value="{{old('description')}}">

            @error('description')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>




        <div>
            <button type="submit" class="btn btn-lg btn-success">Criar Categoria</button>
        </div>
    </form>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')


@section('content')
    <h1>Atualizar Categoria</h1>
    <form action="{{route('admin.categories.update', ['category' => $category->id])}}" method="post">
        @csrf
        @method("PUT")

        <div class="form-group">
            <label>Nome</label>
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{$category->name}}">

            @error('name')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control" value="{{$category->description}}">
        </div>


        <div>
            <button type="submit" class="btn btn-lg btn-success">Atualizar Categoria</button>
        </div>
    </form>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')


@section('content')

    <a href="{{route('admin.categories.create')}}" class="btn btn-lg btn-success">Criar Categoria</a>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        @foreach($categories as $category)
            <tr>
                <td>{{$category->id}}</td>
                <td>{{$category->name}}</td>
                <td width="15%">
                    <div class="btn-group">
                        <a href="{{route('admin.categories.edit', ['category' => $category->id])}}" class="btn btn-sm btn-primary">EDITAR</a>
                        <form action="{{route('admin.categories.destroy', ['category' => $category->id])}}" method="post">
                            @csrf
                            @method("DELETE")
                            <button type="submit" class="btn btn-sm btn-danger">REMOVER</button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection